spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  sql:
    init:
      mode: always
      encoding: UTF-8
      platform: h2
  datasource:
    url:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: javaprojects.test@gmail.com
    password: puqtlmwroiyfcwrv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

register:
  confirm-url: http://localhost:8080/register/confirm

password-reset:
  url: http://localhost:8080/profile/resetPassword
