spring:
  profiles:
    active: dev

  sql:
    init:
      mode: never
      platform: postgresql

  datasource:
    url:
    username:
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: javaprojects.test@gmail.com
    password: puqtlmwroiyfcwrv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

register:
  token-expiration-time: 86400000
  confirm-url: https://javaprojects.ru/projector/register/confirm

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: logs/projector.log
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([%mdc]){yellow} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}'
    file: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%mdc] - %msg%n'